# Generated by Django 5.0.4 on 2024-04-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_details_price_alter_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hari'),
        ),
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
