# Generated by Django 5.0.4 on 2024-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_details_disc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='disc',
            new_name='disccc',
        ),
        migrations.AddField(
            model_name='details',
            name='des',
            field=models.TextField(default='no'),
            preserve_default=False,
        ),
    ]
